source 'http://rubygems.org'

gem 'sinatra'
gem 'rake'
gem 'unicorn'
gem 'sinatra-content-for'
gem 'rake'
gem 'shotgun'
gem 'data_mapper'
gem 'dm-mysql-adapter'
gem 'dm-is-state_machine'
gem 'json'
gem 'openlibrary'
gem 'mail'
gem 'capistrano'
